### PR TITLE
Fixed node not shutting down, if sensor stream breaks (ROS2)

### LINKED ISSUE #181: Color stream breaks silently
**Describe the bug**
On some systems, the color stream breaks down.
This issue is reported in the SDK and the fix will
likely take some time (https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1354).

**To Reproduce**
1. Start the node on any computer using an 'unsupported' usb controler.
   Set 30 fps and color to 2160P
2. rostopic hz /rgb/image_raw
3. Wait some time, hz drops to zero

**Expected behavior**
The node shall crash if the color stream stalls.

The issue here is the 
`if (!k4a_device_.get_capture(&capture, std::chrono::milliseconds(K4A_WAIT_INFINITE)))`
(https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/melodic/src/k4a_ros_device.cpp#L825)
that waits forever in the case that the stream breaks.

I got a tested bugfix and can create a merge request as soon as this issue is approved.

### PR DESCRIPTION
**Pull request by amelhassan**
### Description of the changes:
- This is the ROS2 equivalent change for PR #183: 
"Currently the node will break silently if the camera stops
sending data. This happens as it blocks infinite in
get_capture. This commit reduces the timeout to 5 times
the expected time it would normally take for a new frame
to arrive.
For unknown reasons, the first frame takes way longer to arrive,
therefore we wait up to four seconds for the first frame."

### Required before submitting a Pull Request:
- [x] I reviewed [CONTRIBUTING.md](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/master/CONTRIBUTING.md)
- [x] I [built my changes](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/master/docs/building.md) locally
- [x] I tested my changes with a device
- [x] I changed both the ROS1 and ROS2 branches

### I tested changes on: 
- [ ] Windows
- [x] Linux
- [ ] ROS1
- [x] ROS2

Manual testing

### CODE REVIEW

File: src/k4a_ros_device.cpp [hunk 1]
```diff
@@ -874,12 +874,16 @@ void K4AROSDevice::framePublisherThread()
   calibration_data_.getRgbCameraInfo(depth_rect_camera_info);
   calibration_data_.getDepthCameraInfo(ir_raw_camera_info);
 
+  const std::chrono::milliseconds firstFrameWaitTime = std::chrono::milliseconds(4 * 1000);
+  const std::chrono::milliseconds regularFrameWaitTime = std::chrono::milliseconds(1000 * 5 / params_.fps);
```
Comment (lilustga) [inline src/k4a_ros_device.cpp:878]: [nit] could name these kFirstFrameWaitTime and kRegularFrameWaitTime to show they're constants

File: src/k4a_ros_device.cpp [hunk 2]
```diff
@@ -874,12 +874,16 @@ void K4AROSDevice::framePublisherThread()
   calibration_data_.getRgbCameraInfo(depth_rect_camera_info);
   calibration_data_.getDepthCameraInfo(ir_raw_camera_info);
 
+  const std::chrono::milliseconds firstFrameWaitTime = std::chrono::milliseconds(4 * 1000);
```
Comment (lilustga) [inline src/k4a_ros_device.cpp:877]: Why 4 seconds? Any reason why this length of time?

File: src/k4a_ros_device.cpp (hunk 1 above)
Comment (lilustga) [inline src/k4a_ros_device.cpp:878]: This looks like the loop will be 1/5th the rate of params_.fps, any reason for that?

Comment (amelhassan) [reply src/k4a_ros_device.cpp:878]: For regular frames, the loop will wait up to 5 times the expected amount of time to receive one frame. The wait time is limited so frames are not waited on for an infinite amount of time.

File: src/k4a_ros_device.cpp (hunk 2 above)
Comment (amelhassan) [reply src/k4a_ros_device.cpp:877]: 4 seconds was chosen because the first frame takes longer to arrive unlike the next frames, but 4 seconds is still not overkill for a timeout.

File: src/k4a_ros_device.cpp (hunk 1 above)
Comment (amelhassan) [reply src/k4a_ros_device.cpp:878]: Keeping the same for consistency with the other const in the file.

**Review by lilustga — APPROVED** [review]

File: src/k4a_ros_device.cpp [hunk 3]
```diff
@@ -874,12 +874,16 @@ void K4AROSDevice::framePublisherThread()
...
+  const std::chrono::milliseconds regularFrameWaitTime = std::chrono::milliseconds(1000 * 5 / params_.fps);
+  std::chrono::milliseconds waitTime = firstFrameWaitTime;
+
   while (running_ && rclcpp::ok())
   {
     if (k4a_device_)
     {
       // TODO: consider appropriate capture timeout based on camera framerate
```
Comment (jmachowinski) [inline src/k4a_ros_device.cpp]: The todo is now done, and should be removed

File: src/k4a_ros_device.cpp (hunk 1 above)
Comment (jmachowinski) [reply src/k4a_ros_device.cpp:878]: During normal operation, we see frame drops, especially if color sensor is active and multiple cameras are connected. Waiting UP TO 5 times the time of a frame would need to arrive will not crash the driver on any frame drop.
Also note, this is a timeout, the function will return as soon as a new frame arrives.

Comment (jmachowinski) [reply src/k4a_ros_device.cpp:878]: During normal operation, we see frame drops, especially if color sensor is active and multiple cameras are connected. Waiting UP TO 5 times the time of a frame would need to arrive will not crash the driver on any frame drop.
Also note, this is a timeout, the function will return as soon as a new frame arrives.
